TechEmpower/gemini

pom.xml
I forgot to update the names of the subprojects in the parent `pom.xml`
=> Fix the pom.xml names

README.md, gemini-resin-archetype/src/main/resources/META-INF/maven/archetype.xml, gemini-resin-archetype/src/main/resources/archetype-resources/pom.xml, gemini-resin/README.md
1. Removed a few oversights with `-public` transition.
2. Updated light documentation for starting a new Gemini app from the archetype
=> Fixed some bugs with the archetype

README.md, gemini-resin-archetype/src/main/resources/archetype-resources/pom.xml, gemini/src/main/java/com/techempower/cache/CachedRelation.java, gemini/src/main/java/com/techempower/cache/EntityStore.java, gemini/src/main/java/com/techempower/data/EntityGroup.java, gemini/src/main/java/com/techempower/data/annotation/Left.java, gemini/src/main/java/com/techempower/data/annotation/Relation.java, gemini/src/main/java/com/techempower/data/annotation/Right.java, gemini/src/main/java/com/techempower/gemini/pyxis/JsonWebToken.java
Also, adds the ability to specify both a table name and column names on relations.
Addresses #9
=> Fixes some issues with relation casing

gemini-resin-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/configuration/App-Base.conf, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/configuration/App-__machineName__.conf
=> Disables file logging by default

gemini-resin-archetype/src/main/resources/archetype-resources/database/mysql/migration/00002 Insert Testing Accounts.sql, gemini-resin-archetype/src/main/resources/archetype-resources/database/postgres/changelog.sql, gemini-resin-archetype/src/main/resources/archetype-resources/database/postgres/migration/00000 Create User and Group Tables.sql, gemini-resin-archetype/src/main/resources/archetype-resources/database/postgres/migration/00001 Insert Standard Groups.sql, gemini-resin-archetype/src/main/resources/archetype-resources/database/postgres/migration/00002 Insert Testing Accounts.sql, gemini-resin-archetype/src/main/resources/archetype-resources/database/postgres/migration/00003 Change validation hash.sql
Also, added postgresql migration files.
Addresses #11
=> Documented user credentials

gemini-jndi/LICENSE, gemini-jndi/README.md, gemini-jndi/pom.xml, gemini-jndi/src/main/java/com/techempower/data/jdbc/JndiConnectorFactory.java, pom.xml
This allows Gemini to use a DataSource defined in the servlet container.
=> Add ConnectorFactory that looks up a DataSource via JNDI

gemini/src/main/java/com/techempower/gemini/data/FlywayMigrator.java, pom.xml
Required some minor changes to FlywayMigrator to fix deprecation warnings.
Removed unused Lucene dependencies.
=> Update various dependencies to latest

gemini/src/main/java/com/techempower/data/EntityGroup.java, gemini/src/main/java/com/techempower/data/mapping/DataFieldToMethodMap.java
Allows DataEntities in an EntityStore to have members that are
LocalDate
LocalTime
LocalDateTime
OffsetDateTime
=> Add Entity support for java.time.LocalDateTime and friends

gemini/pom.xml, gemini/src/main/java/com/techempower/gemini/pyxis/JsonWebToken.java, pom.xml
https://github.com/TechEmpower/gemini/issues/35
=> 35: Update jjwt version to one that supports java 9+

gemini-resin-archetype/pom.xml, gemini-resin-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/java/AppEmailTemplater.java, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/java/AppVersion.java, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/java/Application.java, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/java/Security.java, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/java/Server.java, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/java/entities/DataEntity.java, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/java/entities/Group.java, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/java/entities/User.java, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/java/entities/UserToGroup.java, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/java/entities/UserToLogin.java, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/java/handlers/AdminHandler.java, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/java/handlers/HomeHandler.java, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/java/handlers/LoggingExceptionHandler.java, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/java/handlers/UserHandler.java, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/web.xml
=> Update maven archetype to take in a package name

gemini-resin/src/main/java/com/techempower/gemini/HttpRequest.java, gemini/src/main/java/com/techempower/gemini/path/MethodSegmentHandler.java, gemini/src/main/java/com/techempower/gemini/path/NotImplementedHandler.java, gemini/src/main/java/com/techempower/gemini/path/PathDispatcher.java
https://github.com/TechEmpower/gemini/issues/8
=> Return 501 on unsupported http methods

gemini-resin-archetype/src/main/resources/archetype-resources/pom.xml, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/configuration/Base.conf, gemini-resin-archetype/src/main/resources/archetype-resources/src/main/webapp/WEB-INF/configuration/Version.conf
https://github.com/TechEmpower/gemini/issues/7
=> 7: Drop version support

gemini/src/main/java/com/techempower/gemini/data/FlywayMigrator.java, pom.xml
This makes the Flyway version current and enhances the logging a bit when migrations are applied.
=> Flyway bump

pom.xml
Addresses:
https://nvd.nist.gov/vuln/detail/CVE-2019-12384
https://nvd.nist.gov/vuln/detail/CVE-2019-14379
https://nvd.nist.gov/vuln/detail/CVE-2019-14439
https://nvd.nist.gov/vuln/detail/CVE-2019-12814
https://nvd.nist.gov/vuln/detail/CVE-2019-12086
=> Bumping jackson version to fix vulns

pom.xml
Addresses the following:
* [CVE-2019-14540](https://nvd.nist.gov/vuln/detail/CVE-2019-14540)
* [CVE-2019-16335](https://nvd.nist.gov/vuln/detail/CVE-2019-16335)
=> Updates Jackson

gemini/src/main/java/com/techempower/security/SimpleDigester.java
We've been encountering a lot of locking on this. Fetching a new instance
of MessageDigest every time is not that much slower, so we'd rather avoid
the locking.
=> Remove synchronization from SimpleDigester

gemini/src/main/java/com/techempower/Version.java, gemini/src/main/java/com/techempower/gemini/GeminiApplication.java, gemini/src/main/java/com/techempower/gemini/cluster/jms/CacheMessageManager.java, gemini/src/main/java/com/techempower/gemini/lifecycle/InitStartupNotification.java, gemini/src/main/java/com/techempower/gemini/notification/listener/EmailNotificationListener.java
Most importantly: Include the machine name in the subject of notification emails
Also remove some unneeded notifications in the "cluster" package. Those are not useful.
=> Notification cleanup

gemini-hikaricp/src/main/java/com/techempower/data/jdbc/HikariCPConnectorFactory.java
Allow an environment variable to be only part of the value in the
hikari.properties file.
Sorry, I missed the need for this previously.
=> Fix HikariCP env var configuration to support partial string replacement

gemini-hikaricp/pom.xml, gemini-jdbc/pom.xml, gemini-jndi/pom.xml, gemini-log4j12/pom.xml, gemini-log4j2/pom.xml, gemini-logback/pom.xml, gemini-resin-archetype/pom.xml, gemini-resin/pom.xml, gemini/pom.xml, pom.xml
Included in this build:
* #92 Jms Improvements
=> Release 3.3.0

gemini/pom.xml, gemini/src/main/java/com/techempower/gemini/data/LiquibaseMigrator.java, pom.xml
This should work the same as the FlywayMigrator.
=> Provide a Liquibase database migrator as an alternative to Flyway

gemini/src/main/java/com/techempower/gemini/cluster/jms/CacheMessageManager.java
This provides insight into the cache message latency for understanding lag during traffic spikes.
=> Gather cache message latency stats and periodically log a summary

gemini/src/main/java/com/techempower/cache/LruSqlEntityRelation.java
There were problems that arose when running in a multi-instance environment. Fixes:
- Override additional methods so distribution listeners are notified.
- Have reset(Class<T> type) check to ensure the type matches.
- Invalidate LRU cache in add/addAll as explained by the inline comment.
=> Fix deficiencies in LruSqlEntityRelation
