gemini-resin-archetype/pom.xml
gemini-resin/pom.xml
gemini/pom.xml
pom.xml

We now have version [`2.21.0-SNAPSHOT`](https://oss.sonatype.org/content/repositories/snapshots/com/techempower/) and [`2.21.0`](https://oss.sonatype.org/content/repositories/releases/com/techempower/) published, and it required these changes to do.

Updates required in pom.xmls for first release

---

gemini/src/main/java/com/techempower/gemini/cluster/jms/CacheMessageManager.java

A typo caused removing an object to distribute a "reset this entire
entity cache" message, resulting in every instance repopulating its cache
from the database. While this did indeed result in the object no longer
being in the cache, the performance cost was a bit excessive.

Correct cache distribution message type

---

gemini-resin-archetype/src/main/resources/archetype-resources/src/test/resources/db/migration/V2018.08.20.07.07.00__Insert_Testing_Accounts.sql

Without a value for `userlastpasswordchange`, the token reader would throw an exception and never return a valid token (even if the user's token was indeed valid).
This fixes the issue for the test users, and implementations with registration should remember to provide a non-null value to this field.

Fixes JWT not working with test users out of box

---

gemini-jdbc/src/main/java/com/techempower/data/jdbc/ConnectionWrapper.java
gemini-jdbc/src/main/java/com/techempower/data/jdbc/JdbcConnectionProfile.java
gemini-jdbc/src/main/java/com/techempower/data/jdbc/JdbcConnector.java
gemini/src/main/java/com/techempower/gemini/GeminiHelper.java
gemini/src/main/java/com/techempower/gemini/lifecycle/InitDatabaseConnectionTest.java
gemini/src/main/java/com/techempower/helper/CollectionHelper.java

Whether the ConnectionMonitor or the ConnectionWrapper instance is put in client code's try-with-finally block, the gemini-jdbc connection pooling still functions correctly now.
In the future, we should probably consider deprecating ConnectionMonitor to reduce confusion.

Support conventional usage of java.sql.Connection

---

pom.xml

This is a known issue with all JDK11s, and it will presumably be fixed someday, but for now this will do.

Fixes the javadoc stage of building on jdk11

---

gemini/src/main/java/com/techempower/cache/EntityStore.java

- Fix bug where 2 methods failed to notify appropriate CacheListeners.
- Enhance refresh() to accept vararg for the list of IDs to refresh. Since CacheGroup.refresh already accepts a vararg, this aligns with it better.

Notify CacheListeners on calling refresh and removeAll

---

gemini/src/main/java/com/techempower/gemini/email/EmailServerDescriptor.java

This is useful if using the 587 submission port and your server requires
STARTTLS.

Enable STARTTLS

---

gemini-resin/src/main/java/com/techempower/gemini/HttpRequest.java
gemini/src/main/java/com/techempower/gemini/GeminiApplication.java
gemini/src/main/java/com/techempower/gemini/Request.java
gemini/src/main/java/com/techempower/gemini/path/BasicPathHandler.java
gemini/src/main/java/com/techempower/gemini/path/JsonRequestBodyAdapter.java
gemini/src/main/java/com/techempower/gemini/path/MethodSegmentHandler.java
gemini/src/main/java/com/techempower/gemini/path/MethodUriHandler.java
gemini/src/main/java/com/techempower/gemini/path/RequestBodyAdapter.java
gemini/src/main/java/com/techempower/gemini/path/RequestBodyException.java
gemini/src/main/java/com/techempower/gemini/path/StringRequestBodyAdapter.java
gemini/src/main/java/com/techempower/gemini/path/annotation/Body.java
gemini/src/main/java/com/techempower/gemini/path/annotation/ConsumesJson.java
gemini/src/main/java/com/techempower/gemini/path/annotation/ConsumesString.java
gemini/src/main/java/com/techempower/gemini/path/annotation/PathSegment.java
gemini/src/main/java/com/techempower/gemini/pyxis/handler/SecureMethodSegmentHandler.java
gemini/src/main/java/com/techempower/gemini/simulation/SimRequest.java
gemini/src/main/java/com/techempower/js/JacksonJavaScriptReader.java
gemini/src/main/java/com/techempower/js/JavaScriptReader.java

Opening this for initial feedback on the approach.
- Add a new annotation `@Body` indicating that a handler accepts something from the request body
- Add a new interface `RequestBodyAdapter` to be used for transforming the request body into the type needed for the handler method
- Provide convenience default implementations for JSON and Strings, with their own annotations
- Add a JavaScriptReader and default Jackson implementation for the default `JsonRequestBodyAdapter` to use
Example usages:
```java
@Path("foo/{bar}")
@Post
@ConsumesJson
public boolean handleFoo(String bar, MyView body) {
// handler logic...
}
```
(Using `method.getGenericParameterTypes()` allows the handler method to accept types with generics, for example `Map<String, Object> body`)
The `@Body` annotation can also …

Extended request body support

---

gemini/src/main/java/com/techempower/gemini/cluster/jms/CacheMessageManager.java

It is possible for different instances of an application to make different
choices about whether to cache an entity or not. If one instance is caching
it, it correctly sends updates out over the message queue to other
instances. But if a non-caching instance receives such a message, it's not
actually an error. Ignore instead of throwing an exception.

Stop throwing an exception for a situation that is not an error

---

gemini/src/main/java/com/techempower/gemini/path/JsonRequestBodyAdapter.java

It is pretty common to send additional parameters in the Content-Type, such as 'Content-Type: application/json; charset=UTF-8'. This change adds support for other parameters.

Add support for multiple content-type parameters in JSON request body

---

.travis.yml
gemini-resin-archetype/src/main/resources/archetype-resources/pom.xml
pom.xml

Fixes the failing build in a few unrelated ways:
1. After a quick Google search for 
> Expected feature release number in range of 9 to 14, but got: 8
the Travis CI issue appears to be solved by setting a certain property in the `.travis.yml` file. See [this thread](https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/6) for details.
2. Changing the targeted version of the maven war plugin to one that exists. `3.1.0`  is the latest `3.1.x` according to [Maven](https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-war-plugin), `3.1.1` does not exist.
3. Changes the `javax.servlet-api` dependency in the archetype to be required at compile time to address another compilation issue.

Fix Failing Build

---

gemini/src/main/java/com/techempower/cache/EntityStore.java
gemini/src/main/java/com/techempower/data/EntityGroup.java

I opened up every single file in the entire repo, one by one, to see what errors IntelliJ would report, and "fixed" them in ways that I'm hoping Eclipse won't try to simplify back into their original forms.
Note: None of these are actual compilation errors, but IntelliJ seems to think they are. Also, one of the issues isn't actually being reported as a compilation error, but it might as well be fixed now (it's an incorrectly named/documented javadoc parameter).

Fix various "compilation errors"

---

gemini/src/main/java/com/techempower/gemini/path/MethodUriHandler.java

TL;DR: Adds support for custom path segment types in `MethodUriHandler`.
TL: This should allow any class with a static method named either `fromString` or `valueOf` that accepts a single `String` argument to be used as a method param for a path segment in a `PathUriHandler` method. For example, where previously you might have had:
```java
@Get
@Path("{id}")
public boolean getById(String idStr) {
UUID id = UUID.fromString(idStr);
// ...
}
```
you can now do
```java
@Get
@Path("{id}")
public boolean getById(UUID id) {
// ...
}
```
The `fromString` method takes priority over `valueOf`. As a result, custom enum conversion can be achieved by simply defining a `fromString` method (so that it doesn't use the implicitly defined `valueOf` method). This also has the added benefit of supporting the …

New Path Segment Types

---

gemini-hikaricp/src/main/java/com/techempower/data/jdbc/HikariCPConnectorFactory.java
pom.xml

Using the same macro-replacement tags as Gemini configuration, add support for referencing environment variables in hikari.properties.
Also update to the current version of HikariCP.

Support referencing environment variables in hikari.properties

---

gemini/src/main/java/com/techempower/gemini/GeminiConstants.java

There are some build scenarios where there may be multiple Gemini libraries
with different versions. If the Gemini JAR file, this will find the exact
version. If not the JAR, then this is a little closer to giving us the
highest available version among those found.

Improve identifying Gemini version

---

gemini/src/main/java/com/techempower/cache/CacheGroup.java
gemini/src/main/java/com/techempower/cache/EntityStore.java
gemini/src/main/java/com/techempower/cache/LruCacheGroup.java
gemini/src/main/java/com/techempower/cache/PureMemoryGroup.java
gemini/src/main/java/com/techempower/cache/SubsetCacheGroup.java
gemini/src/main/java/com/techempower/data/EntityGroup.java
gemini/src/main/java/com/techempower/gemini/cluster/jms/CacheMessageManager.java

1. Add various raw*() methods to EntityGroup to allow SubsetCacheGroup to
call those implementations directly as needed.
2. Delete CacheGroup.select() because it seems obsolete and not worth
accounting for in SubsetCacheGroup. I'm open to keeping it if desired.

Add SubsetCacheGroup

---

gemini/src/main/java/com/techempower/gemini/cluster/jms/AsyncConsumer.java
gemini/src/main/java/com/techempower/gemini/cluster/jms/AsyncSubscriber.java
gemini/src/main/java/com/techempower/gemini/cluster/jms/BlockingConsumer.java
gemini/src/main/java/com/techempower/gemini/cluster/jms/BlockingReceiver.java
gemini/src/main/java/com/techempower/gemini/cluster/jms/BlockingSubscriber.java
gemini/src/main/java/com/techempower/gemini/cluster/jms/CacheMessageManager.java
gemini/src/main/java/com/techempower/gemini/cluster/jms/GeminiProducer.java
gemini/src/main/java/com/techempower/gemini/cluster/jms/GeminiPublisher.java
gemini/src/main/java/com/techempower/gemini/cluster/jms/GeminiSender.java

1. Allow providing separate ConnectionFactories for publish and subscribe, so the publish one can be a pooled connection.
2. Allow configuring the deliveryMode of the publisher, so an implementation can use NON_PERSISTED if desired.
3. Remove some deprecated constructors.

Jms improvements

---

gemini/src/main/java/com/techempower/cache/CacheGroup.java
gemini/src/main/java/com/techempower/cache/EntityStore.java
gemini/src/main/java/com/techempower/cache/LruCacheGroup.java
gemini/src/main/java/com/techempower/cache/PureMemoryGroup.java
gemini/src/main/java/com/techempower/data/EntityGroup.java
gemini/src/main/java/com/techempower/gemini/cluster/jms/CacheMessageManager.java

When useAffectedRows is available, use that to determine whether put()
actually affected rows in the database. If not, don't bother updating the
methodValueCache or notifying the listeners.
This is most valuable as a way to avoid sending pointless JMS messages via
CacheMessageManager.

Optionally skip updating methodValueCache/listeners when nothing updated

---

gemini/src/main/java/com/techempower/cache/CacheGroup.java
gemini/src/main/java/com/techempower/cache/PureMemoryGroup.java
gemini/src/main/java/com/techempower/data/EntityGroup.java

Specifying EntityGroup.NO_COMPARATOR() will skip maintaining a sorted list
of entities and avoid the attendant sync locks and data structure updates.

Optionally support disabling maintaining a sorted list in CacheGroup

---

gemini/src/main/java/com/techempower/helper/DateHelper.java

Move pre-calculated values into an object that can be marked volatile to ensure double-checked locking works correctly.

Fix DateHelper sync lock bug

---

gemini/src/main/java/com/techempower/gemini/Configurator.java

This helps to ensure if the multi-threaded configuration process experiences a catastrophic failure there is some more helpful logging to investigate the problem.

Better log catastrophic configuration failures on startup

---

gemini/src/main/java/com/techempower/cache/EntityStore.java
gemini/src/main/java/com/techempower/cache/annotation/Indexed.java
gemini/src/main/java/com/techempower/data/EntityGroup.java
gemini/src/main/java/com/techempower/gemini/cluster/jms/CacheMessageManager.java

Previously, using the @Indexed annotation on a data entity method would
only work within a single instance. With this change, CacheMessageManager
will update the method value cache as needed.
Note: As commented in several places in this commit, every entity that uses
@Indexed must have its EntityGroup "distribute" attribute set to true for
this to work.

Make CacheMessageManager support the EntityStore method value cache

---

gemini-resin/src/main/java/com/techempower/gemini/LegacyContext.java
gemini-resin/src/main/java/com/techempower/gemini/jsp/NullServletOutputStream.java
gemini-resin/src/main/java/com/techempower/gemini/jsp/RedirectedServletOutputStream.java
gemini/src/main/java/com/techempower/gemini/data/DatabaseMigrator.java
gemini/src/main/java/com/techempower/gemini/data/FlywayMigrator.java
gemini/src/main/java/com/techempower/gemini/lifecycle/InitDatabaseMigrations.java
pom.xml

- applyMigrations: By default true when NOT production. Configurable.
- abortStartupIfPending: By default true. Configurable.
- Update Flyway, HikariCP versions
This gives us the flexibility to automatically apply migrations in some
environments, and not in others. By default, migrations are applied
automatically everywhere EXCEPT production, where it is expected migrations
will be applied manually. Also, instances will refuse to start if there are
pending migrations.

Database Migration enhancements

---

gemini/src/main/java/com/techempower/cache/CacheGroup.java
gemini/src/main/java/com/techempower/data/EntityGroup.java

Fixes #105. Relatively difficult to demonstrate, but I verified it fixes the issue by replicating it with a local Gemini project, and breakpoints in my IDE set up to pause a thread in `CacheGroup#get` on the right line for 100ms while another thread is resetting the cache for that group. Afterwards I targeted a build of this branch after which I could no longer replicate the issue with the breakpoints in the same places as before.

Fix cache group race condition

---

gemini/src/main/java/com/techempower/gemini/data/LiquibaseMigrator.java

Previously listPendingMigrations() would return an empty list if an exception was caught, which was a lie because we don't know the migration state.

Properly treat a Liquibase exception as unknown migration state

---

gemini/src/main/java/com/techempower/cache/MethodValueCache.java

MethodValueCache's getObjects() implementation was fine for a CacheGroup
because everything was already in memory and fast to fetch. However, an
EntityGroup would end up doing a separate query for every requested entity
and this could be quite slow.
This change simply uses the existing functionality of map() to get all
requested entities in a single query so it is faster for an EntityGroup.
Performance for CacheGroups is not impacted significantly.

Improve performance of getObjects() for EntityGroup

---

gemini/src/main/java/com/techempower/gemini/GeminiApplication.java

When the site is down, it shows an error message but the HTTP code is the
default of 200. This is a problem for load balancers seeing the application
as healthy when it is not.

Set HTTP status 500 when site is unavailable

---

gemini/src/main/java/com/techempower/cache/CachedRelation.java
gemini/src/main/java/com/techempower/cache/CachingEntityRelation.java
gemini/src/main/java/com/techempower/cache/EntityStore.java
gemini/src/main/java/com/techempower/cache/LruCacheGroup.java
gemini/src/main/java/com/techempower/cache/LruSqlEntityRelation.java
gemini/src/main/java/com/techempower/data/SqlEntityRelation.java
gemini/src/main/java/com/techempower/gemini/cluster/jms/CacheMessageManager.java

This provides a middle ground for applications with large relations and entity groups so they don't need to be fully cached (using all that heap space) but can still benefit from LRU caching and otherwise be used similar to when cached and get CacheMessageManager updates appropriately.
Note that for both LruCacheGroup and LruSqlEntityRelation, client code will want to continue to avoid operations that result in reading the full table into memory. These changes enable an application to treat these closer to their fully-cached counterparts, but client code must still beware of the performance consequences of an LruCacheGroup.list() or LruSqlEntityRelation.replaceAll() or removeAll().
- SqlEntityRelation
- Builder needed its members to be protected so they could be used by the new subclass …

More fully support LRU caching for EntityGroups and EntityRelations.

---

gemini/src/main/java/com/techempower/gemini/Context.java
gemini/src/main/java/com/techempower/gemini/context/SessionNamedValues.java

Fix an issue where logout would correctly invalidate the session, but the Context.session remained the invalidated one so any subsequent changes to session values during that response would be lost. This change clears Context.session so a new session is created as needed and available for use during this response, instead of needing to wait for a subsequent request for the new session to be available.

When invalidating the session make it possible to start using a new one
